name: Deploy release candidate

on:
  workflow_dispatch:

jobs:
  deploy_release_candidate:
    name: Calculate version
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - uses: actions/checkout@v3
        with:
          ref: testing
          fetch-depth: 0

      - name: Log
        run: echo "Triggered deploy release candidate"
