name: Deploy release candidate

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Name of branch release candidate'
        required: true
        type: string

jobs:
  deploy:
    name: Build and deploy with EAS
    runs-on: ubuntu-latest
    environment: TEST

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch_name }}
          fetch-depth: 0
