name: Deploy release

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Build and deploy with EAS
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
