name: Post run test

on:
  workflow_dispatch:
    inputs:
      pull_request_id:
        description: "ID of the pull request"
        required: true
      message:
        description: "Message"
        required: true

jobs:
  create_message:
    runs-on: ubuntu-latest
    steps:
      - name: Reply 'Running e2e test' message with test result
        uses: actions/github-script@v6
        id: create_reply
        with:
          script: |
            console.log('owner', context.repo.owner)
            console.log('repo', context.repo.repo)

            const comments = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: '${{ github.event.inputs.pull_request_id }}',
              per_page: 100,
            })

            const sortedComments = comments.data.sort((a, b) => {
              return new Date(b.submitted_at) - new Date(a.submitted_at);
            });

            const comment = sortedComments.find(comment => comment.body == commentBody)

            if (!comment) {
              core.setFailed('Comment not found');
            }

            console.log(comment)

            await github.rest.pulls.createReplyForReviewComment({
              owner,
              repo,
              pull_number: '${{ github.event.inputs.pull_request_id }}',
              comment_id: comment.id,
              body: '${{ github.event.inputs.message }}',
            });

            const repliesResponse = await github.rest.pulls.listCommentsForReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: '${{ github.event.inputs.pull_request_id }}',
              review_id: comment.id,
            });

            const replies = repliesResponse.data;

            if (replies.length < 2) {
              core.setFailed('No replies');
            }

            const androidComment = replies.find(reply => reply.body.contains("ANDROID"))
            const iosComment = replies.find(reply => reply.body.contains("IOS"))

            if (!androidComment || !iosComment) {
              core.setFailed('Android or iOS not found');
            }

            const isAllTestsPassed = replies.every(reply => reply.body.contains('PASSED'))

            if (!isAllTestsPassed) {
              core.setFailed('One or both tests failed for Android or iOS');
              return
            }

            await octokit.rest.pulls.dismissReview({
              owner,
              repo,
              pull_number: '${{ github.event.inputs.pull_request_id }}',
              review_id: comment.id,
              message: 'All tests passed ✅',
            });
