name: Branch Merge Workflow

on:
  pull_request:
    branches:
      - testing
    types:
      - closed

jobs:
  release_candidate_merge:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release-candidate/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run action for release-candidate merge
        run: echo "Merged release-candidate into testing"

      - run: echo ${{ github.ref_name }}

  hotfix_merge:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'hotfix/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run action for hotfix merge
        run: echo "Merged hotfix into testing"

      - run: echo ${{ github.ref_name }}
