name: Post-Merge Actions on Testing

on:
  push:
    branches:
      - testing

jobs:
  post_merge_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

       - name: Determine if release-candidate or hotfix
          run: |
            if git describe --tags | grep -q "release-candidate"; then
              echo "Release candidate merge detected"
              # Run commands for release-candidate merge
            elif git describe --tags | grep -q "hotfix"; then
              echo "Hotfix merge detected"
              # Run commands for hotfix merge
            else
              echo "Unknown merge type"
