name: Post run test

on:
  workflow_dispatch:
    inputs:
      pull_request_id:
        description: "ID of the pull request"
        required: true
      review_comment_id:
        description: "ID of review comment"
        required: true
      message:
        description: "Message"
        required: true

jobs:
  postTest:
    runs-on: ubuntu-latest
    steps:
      - name: Reply 'Running e2e test' message with test result
        uses: actions/github-script@v6
        if: false
        id: create_reply
        with:
          script: |
            const response = await github.rest.pulls.createReplyForReviewComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: '${{ github.event.inputs.pull_request_id }}',
              comment_id: '${{ github.event.inputs.review_comment_id }}',
              body: '${{ github.event.inputs.message }}',
            });
      
      - name: Resolve conversation
        uses: actions/github-script@v6
        id: resolve_conversation
        with:
          script: |
            const comment = await github.rest.pulls.getReviewComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: '${{ github.event.inputs.review_comment_id }}',
            });

            const reviewComments = await github.rest.pulls.listReviewComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: '${{ github.event.inputs.pull_request_id }}',
            });

            const commentsReplies = reviewComments.data.filter(reply => reply.in_reply_to_id == comment.data.id)

            if (commentsReplies.length < 2) {
              core.setFailed('No replies');
            }

            const androidComment = commentsReplies.find(reply => reply.body.contains("ANDROID"))
            const iosComment = commentsReplies.find(reply => reply.body.contains("IOS"))

            if (!androidComment || !iosComment) {
              core.setFailed('Android or iOS not found');
            }

            const isAllTestsPassed = commentsReplies.every(reply => reply.body.contains('PASSED'))

            if (!isAllTestsPassed) {
              core.setFailed('One or both tests failed for Android or iOS');
              return
            }

            const response = await github.rest.pulls.dismissReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: '${{ github.event.inputs.pull_request_id }}',
              review_id: comment.data.pull_request_review_id,
              message: 'All tests passed ✅',
            });

            console.log("<===================================================>");
            console.log(response);
            console.log("<===================================================>");
