name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Build and run tests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    environment: DEV

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for existing 'Running e2e tests' comment
        uses: actions/github-script@v6
        id: check_comment
        with:
          script: |
            const pull_number = context.issue.number;
            const commentBody = "Running e2e test";

            const comments = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              per_page: 100,
            })

            const sortedComments = comments.data.sort((a, b) => {
              return new Date(b.submitted_at) - new Date(a.submitted_at);
            });

            const hasRunningTestComment = sortedComments.find(comment => comment.body == commentBody)

            if (hasRunningTestComment) {
              const repliesResponse = await github.rest.pulls.listCommentsForReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pull_number,
                review_id: hasRunningTestComment.id,
              });

              const replies = repliesResponse.data;

              if (replies.length < 2) {
                core.setOutput("skip_next_steps", true);
                return
              }

              const androidComment = replies.find(reply => reply.body.includes("ANDROID"))
              const iosComment = replies.find(reply => reply.body.includes("IOS"))

              if (!androidComment || !iosComment) {
                core.setOutput("skip_next_steps", true);
                return
              }

              const isAllTestsPassed = replies.every(reply => reply.body.includes('PASSED'))

              if (isAllTestsPassed) {
                core.setOutput("skip_next_steps", true);
                return
              }

              core.setOutput("skip_next_steps", false);
              return
            }

            core.setOutput("skip_next_steps", false);

      - name: Add PR number in build success hook file
        if: github.event_name == 'pull_request' && steps.check_comment.outputs.skip_next_steps == 'true'
        run: sed -i "2s/^/PULL_REQUEST_ID=${{ github.event.number }}\n/" scripts/eas-build-on-success.sh

      - name: Create 'Running e2e test' review comment
        uses: actions/github-script@v6
        id: create_review_comment
        if: steps.check_comment.outputs.skip_next_steps == 'true'
        with:
          script: |
            const pull_number = context.issue.number;
            const comment = "Running e2e test";

            const filesChanged = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
            });

            const firstFileChanged = filesChanged.data[0]

            const review = await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              event: 'REQUEST_CHANGES',
              body: comment,
              comments: [
                {
                  path: firstFileChanged.filename,
                  position: 1,
                  body: comment
                }
              ]
            });

            const reviewComments = await github.rest.pulls.listReviewComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
            });

            const reviewComment = reviewComments.data[0]
            console.log(reviewComment)
            
            if (!reviewComment) {
              core.setFailed('Comment not found');
            }

            core.setOutput("comment_id", reviewComment.id);

      - name: Add comment ID to build success hook file
        if: steps.check_comment.outputs.skip_next_steps == 'true'
        run: sed -i "3s/^/COMMENT_ID=${{ steps.create_review_comment.outputs.comment_id }}\n/" scripts/eas-build-on-success.sh

      - name: Extract branch name
        shell: bash
        id: extract_branch
        if: steps.check_comment.outputs.skip_next_steps == 'true'
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Add branch name to build success hook file
        if: steps.check_comment.outputs.skip_next_steps == 'true'
        run: sed -i "4s/^/BRANCH=${{ steps.extract_branch.outputs.branch }}\n/" scripts/eas-build-on-success.sh

      - name: Cat scripts/eas-build-on-success.sh
        if: steps.check_comment.outputs.skip_next_steps == 'true'
        run: cat scripts/eas-build-on-success.sh
