name: Create release candidate

on:
  workflow_dispatch:

jobs:
  create_release_candidate_branch:
    name: Calculate version
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - uses: actions/checkout@v3
        with:
          ref: testing
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2

      - name: Create release candidate branch
        run: |
          git fetch
          git pull
          git checkout -b release-candidate/2.0.0
          git remote set-url origin https://github.com/iurybrasileiro/gb_actions.git
          git push origin release-candidate/2.0.0

      - name: Reply 'Running e2e test' message with test result
        uses: actions/github-script@v6
        id: create_reply
        with:
          script: |
            const response = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'release-candidate/2.0.0',
              base: 'testing',
            });

            console.log(response)
